version: "3"

services:
  hbase:
    image: lenchv/kerberized-hbase:1.0
    healthcheck:
      test: "(printf hbase | kinit hbase@KERBEROS.SERVER && curl -f https://localhost:50470 --insecure && curl -f https://localhost:50075 --insecure && curl -f --negotiate -u : http://volodymyr.local:8080) || exit 1"
    ports:
      - "16010:16010"
      - "8085:8085"
      - "8080:8080"
    hostname: volodymyr.local
    volumes:
      - ./kerberos/krb5.conf:/etc/krb5.conf
      - krb-server:/opt/keytabs/
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - kerberos.server
    environment:
      HBASE_MANAGES_ZK: "false"
      KRB_ROOT_PASSWORD: root
  kerberos.server:
    build: lenchv/hbase-kerberos-server:1.0
    container_name: hbase.driver_kerberos.server
    hostname: volodymyr.local
    ports:
      - "749:749"
      - "88:88"
    environment:
      REALM: KERBEROS.SERVER
      DOMAIN_REALM: kerberos.server
      KERBEROS_ROOT_USER_PASSWORD: root
      CLIENT_USER: hbase
      CLIENT_PASS: hbase
    volumes:
      - krb-server:/opt/keytabs/
      - /etc/localtime:/etc/localtime:ro
volumes:
  krb-server:
