version: "3"

services:
  hbase:
    build: hbase/
    healthcheck:
      test: (curl -f https://localhost:50470 --insecure && curl -f https://localhost:50075 --insecure) || exit 1
    ports:
      - "16010:16010"
      - "8085:8085"
      - "8080:8080"
    hostname: hackolade.local
    volumes:
      - ./kerberos/krb5.conf:/etc/krb5.conf
      - krb-server:/opt/keytabs/
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - zookeeper
      - kerberos.server
    environment:
      HBASE_MANAGES_ZK: "false"
  kerberos.server:
    build:
      dockerfile: Server.dockerfile
      context: ./kerberos/
    container_name: hbase.driver_kerberos.server
    hostname: hackolade.local
    ports:
      - "749:749"
      - "88:88"
    environment:
      REALM: KERBEROS.SERVER
      DOMAIN_REALM: kerberos.server
      KERBEROS_ROOT_USER_PASSWORD: root
      CLIENT_USER: hbase
      CLIENT_PASS: hbase
    volumes:
      - krb-server:/opt/keytabs/
      - /etc/localtime:/etc/localtime:ro
volumes:
  krb-server:
