version: "3"

services:
  zookeeper:
    image: zookeeper
    hostname: hackolade.local
    ports:
      - "2181:2181"
  hbase:
    build: hbase/
    ports:
      - "16010:16010"
      - "8085:8085"
      - "8080:8080"
    # command: bash -c "chown hive:hive /opt/hive.keytab && kinit hive/hive.driver@KERBEROS.SERVER -k -t /opt/hive.keytab && /opt/apache-hive-2.3.6-bin/bin/hiveserver2"
    hostname: hackolade.local
    volumes:
      - ./confs/hbase/hbase-site.xml:/opt/hbase-2.2.3/conf/hive-site.xml
    #   - ./ssl/:/opt/ssl/
    #   - ./krb/krb5.conf:/etc/krb5.conf
    #   - ./krb/hive.keytab:/opt/hive.keytab
    #   - ./krb/core-site.xml:/opt/hadoop-2.9.2/etc/hadoop/core-site.xml
    #   - ./krb/hdfs-site.xml:/opt/hadoop-2.9.2/etc/hadoop/hdfs-site.xml
    #   - ./krb/yarn-site.xml:/opt/hadoop-2.9.2/etc/hadoop/yarn-site.xml
    #   - ./krb/mapred-site.xml:/opt/hadoop-2.9.2/etc/hadoop/mapred-site.xml
    environment:
      - HBASE_MANAGES_ZK=false
    env_file:
      - ./hadoop.env
  kerberos.server:
    image: sequenceiq/kerberos:1.1
    container_name: hbase.driver_kerberos.server
    hostname: kerberos.server
    ports:
      - "749:749"
      - "88:88"
    environment:
      REALM: KERBEROS.SERVER
      DOMAIN_REALM: kerberos.server
  # Hadoop
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    ports:
      - 50070:50070
      - 9000:9000
    environment:
      - CLUSTER_NAME=hackolade.local
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
